# Generated by Django 4.2.10 on 2024-03-07 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_user_experience"),
        ("characters", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="charactersmodel",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="characters",
                to="user.user",
            ),
        ),
    ]
