# Generated by Django 4.2.10 on 2024-03-07 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_user_experience"),
        ("characters", "0002_charactersmodel_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="charactersmodel",
            options={"verbose_name": "Персонаж", "verbose_name_plural": "Персонажи"},
        ),
        migrations.AlterField(
            model_name="charactersmodel",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="characters",
                to="user.user",
            ),
        ),
    ]
