# Generated by Django 4.2.10 on 2024-03-07 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_user_experience"),
        ("characters", "0003_alter_charactersmodel_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="charactersmodel",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="characters",
                to="user.user",
            ),
        ),
    ]
