# Generated by Django 4.2.10 on 2024-03-11 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0004_alter_charactersmodel_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="charactersmodel",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
