# Generated by Django 4.2.10 on 2024-05-07 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("embed", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommandModels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.CharField(max_length=500)),
                ("enabled", models.BooleanField()),
                (
                    "embed_message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="embed.embedmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Команда",
                "verbose_name_plural": "Команды",
            },
        ),
    ]
