# Generated by Django 4.2.10 on 2024-05-07 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("embed", "0001_initial"),
        ("commands", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CommandModels",
            new_name="CommandsModel",
        ),
    ]
