# Generated by Django 4.2.10 on 2024-05-07 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("commands", "0002_rename_commandmodels_commandsmodel"),
    ]

    operations = [
        migrations.RenameField(
            model_name="commandsmodel",
            old_name="embed_message",
            new_name="embed_name",
        ),
    ]
