# Generated by Django 4.2.10 on 2024-05-07 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("commands", "0003_rename_embed_message_commandsmodel_embed_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="commandsmodel",
            old_name="embed_name",
            new_name="embed",
        ),
    ]
