# Generated by Django 4.2.10 on 2024-03-07 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0002_alter_inventorymodel_characters"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemsModel",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "inventory",
                    models.ManyToManyField(
                        related_name="items",
                        related_query_name="item",
                        to="inventory.inventorymodel",
                    ),
                ),
            ],
        ),
    ]
