# Generated by Django 4.2.10 on 2024-03-07 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="itemsmodel",
            options={"verbose_name": "Предмет", "verbose_name_plural": "Предметы"},
        ),
    ]
