# Generated by Django 4.2.10 on 2024-03-11 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0002_alter_itemsmodel_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemsmodel",
            name="description",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="itemsmodel",
            name="name",
            field=models.CharField(default="a", max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="itemsmodel",
            name="rarity",
            field=models.CharField(
                choices=[
                    ("com", "common"),
                    ("unc", "uncommon"),
                    ("rar", "rarest"),
                    ("epc", "epic"),
                    ("leg", "legendary"),
                ],
                default="com",
                max_length=3,
            ),
            preserve_default=False,
        ),
    ]
