# Generated by Django 4.2.10 on 2024-03-11 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_alter_inventorymodel_options"),
        ("items", "0003_itemsmodel_description_itemsmodel_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="itemsmodel",
            name="inventory",
        ),
        migrations.AddField(
            model_name="itemsmodel",
            name="is_stackable",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="ItemInInventoryModel",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("count", models.IntegerField()),
                (
                    "inventory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory",
                        related_query_name="inventory",
                        to="inventory.inventorymodel",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        related_query_name="item",
                        to="items.itemsmodel",
                    ),
                ),
            ],
        ),
    ]
