# Generated by Django 4.2.10 on 2024-03-11 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_alter_inventorymodel_options"),
        ("items", "0004_remove_itemsmodel_inventory_itemsmodel_is_stackable_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ItemInInventoryModel",
            new_name="ItemsInInventoryModel",
        ),
    ]
