# Generated by Django 4.2.10 on 2024-03-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0005_rename_itemininventorymodel_itemsininventorymodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="EquippedItemModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="itemsininventorymodel",
            options={
                "verbose_name": "Предмет в инвентаре",
                "verbose_name_plural": "Предметы в инвентаре",
            },
        ),
        migrations.AddField(
            model_name="itemsmodel",
            name="equipment_slot",
            field=models.CharField(
                choices=[
                    ("hea", "head"),
                    ("bod", "body"),
                    ("leg", "legs"),
                    ("fee", "feet"),
                    ("rhd", "right hand"),
                    ("lhd", "left hand"),
                    ("thd", "two hand"),
                    ("non", "not equipped"),
                ],
                default="non",
                max_length=3,
            ),
        ),
    ]
