# Generated by Django 4.2.10 on 2024-03-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0007_alter_itemsmodel_rarity"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemsmodel",
            name="is_used",
            field=models.BooleanField(default=False),
        ),
    ]
