# Generated by Django 4.2.10 on 2024-03-11 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0004_alter_charactersmodel_user"),
        ("items", "0008_itemsmodel_is_used"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="equippeditemmodel",
            options={
                "verbose_name": "Экиперованый предмет",
                "verbose_name_plural": "Экиперованные предметы",
            },
        ),
        migrations.AddField(
            model_name="equippeditemmodel",
            name="character",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="characters.charactersmodel",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="equippeditemmodel",
            name="equipment_slot",
            field=models.CharField(
                choices=[
                    ("hea", "head"),
                    ("bod", "body"),
                    ("leg", "legs"),
                    ("fee", "feet"),
                    ("rhd", "right hand"),
                    ("lhd", "left hand"),
                    ("thd", "two hand"),
                    ("non", "not equipped"),
                ],
                default=1,
                max_length=3,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="equippeditemmodel",
            name="item",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="items.itemsmodel",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="equippeditemmodel",
            name="id",
            field=models.IntegerField(
                auto_created=True, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="itemsininventorymodel",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="item",
                related_query_name="item",
                to="items.itemsmodel",
            ),
        ),
    ]
