# Generated by Django 4.2.10 on 2024-03-12 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0005_alter_charactersmodel_id"),
        ("inventory", "0004_alter_inventorymodel_id"),
        ("items", "0010_alter_equippeditemmodel_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equippeditemmodel",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="characters.charactersmodel",
            ),
        ),
        migrations.AlterField(
            model_name="itemsininventorymodel",
            name="inventory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="inventory.inventorymodel",
            ),
        ),
        migrations.AlterField(
            model_name="itemsininventorymodel",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="items.itemsmodel"
            ),
        ),
    ]
