# Generated by Django 4.2.10 on 2024-03-07 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("characters", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryModel",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "characters",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="characters.charactersmodel",
                    ),
                ),
            ],
        ),
    ]
