# Generated by Django 4.2.10 on 2024-03-07 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_alter_inventorymodel_characters"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inventorymodel",
            options={"verbose_name": "Инвентарь", "verbose_name_plural": "Инвентари"},
        ),
    ]
