# Generated by Django 4.2.10 on 2024-03-11 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("characters", "0004_alter_charactersmodel_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="CharacterStatsModel",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("stat_name", models.CharField(max_length=50)),
                ("stat_value", models.IntegerField()),
                (
                    "characters",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="characters.charactersmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Характеристика персонажа",
                "verbose_name_plural": "Характеристики персонажа",
            },
        ),
    ]
