# Generated by Django 4.2.10 on 2024-03-11 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="characterstatsmodel",
            name="characters",
        ),
        migrations.AddField(
            model_name="characterstatsmodel",
            name="description",
            field=models.TextField(default=None, null=True),
        ),
    ]
