# Generated by Django 4.2.10 on 2024-03-11 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0003_rename_characterstatsmodel_statsmodel"),
    ]

    operations = [
        migrations.RenameField(
            model_name="statsmodel",
            old_name="stat_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="statsmodel",
            old_name="stat_value",
            new_name="value",
        ),
    ]
