# Generated by Django 4.2.10 on 2024-03-11 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0004_rename_stat_name_statsmodel_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="statsmodel",
            options={
                "verbose_name": "Характеристика",
                "verbose_name_plural": "Характеристики",
            },
        ),
    ]
