# Generated by Django 4.2.10 on 2024-03-12 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0005_alter_charactersmodel_id"),
        ("items", "0011_alter_equippeditemmodel_character_and_more"),
        ("stats", "0006_alter_statsmodel_id_itemstatsmodel_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="characterstatsmodel",
            options={
                "verbose_name": "Характеристика персонажа",
                "verbose_name_plural": "Характеристики персонажей",
            },
        ),
        migrations.AlterModelOptions(
            name="itemstatsmodel",
            options={
                "verbose_name": "Характеристика предмета",
                "verbose_name_plural": "Характеристики предметов",
            },
        ),
        migrations.AlterField(
            model_name="characterstatsmodel",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stats",
                to="characters.charactersmodel",
            ),
        ),
        migrations.AlterField(
            model_name="itemstatsmodel",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stats",
                to="items.itemsmodel",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="characterstatsmodel",
            unique_together={("character", "stat")},
        ),
        migrations.AlterUniqueTogether(
            name="itemstatsmodel",
            unique_together={("item", "stat")},
        ),
    ]
