# Generated by Django 4.2.10 on 2024-03-06 03:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_registration_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_activity_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="user",
            name="registration_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
