# Generated by Django 4.2.10 on 2024-03-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_user_last_activity_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="experience",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
