# Generated by Django 4.2.10 on 2024-03-12 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_user_characters_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
