# Generated by Django 4.2.10 on 2024-03-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_alter_user_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="characters_count",
            field=models.IntegerField(default=2),
        ),
    ]
